"""Type stubs for dreame_mocker.const."""

from enum import IntEnum


class DeviceState(IntEnum):
    SWEEPING = ...
    IDLE = ...
    PAUSED = ...
    ERROR = ...
    RETURNING = ...
    CHARGING = ...
    MOPPING = ...
    DRYING = ...
    WASHING = ...
    SWEEP_AND_MOP = ...
    CHARGE_COMPLETE = ...
    MOP_WASHING = ...
    MOP_WASHING_PAUSED = ...


# Property values are (siid, piid) tuples used as dict keys.
class Property:
    STATE: tuple[int, int]
    BATTERY_LEVEL: tuple[int, int]
    ERROR: tuple[int, int]
    SUCTION_LEVEL: tuple[int, int]
    WATER_VOLUME: tuple[int, int]
    CLEANING_MODE: tuple[int, int]
    CLEANING_TIME: tuple[int, int]
    CLEANING_AREA: tuple[int, int]
    MAIN_BRUSH_LIFE_LEVEL: tuple[int, int]
    SIDE_BRUSH_LIFE_LEVEL: tuple[int, int]
    FILTER_LIFE_LEVEL: tuple[int, int]
    MOP_PAD_LIFE_LEVEL: tuple[int, int]
    DND_ENABLED: tuple[int, int]
    VOLUME: tuple[int, int]


STATES: dict[int, str]
